Repository sHedC/python-masterthermconnect, pull requests merged in 2023-01, with the labels that each got.

#56 SHedC/issue55
  README.md
Labels: documentation

#58 Fix HC1 Ambient Temperature Mapping
  masterthermconnect/const.py
Labels: bug

#61 Hc0_ambient_requested now wrong
  masterthermconnect/const.py
Labels: bug

#63 Re-Check Pad and Internal Setup
  masterthermconnect/const.py
  masterthermconnect/controller.py
  tests/fixtures/newapi/pumpdata_10021_1_0.json
  tests/test_config_data.py
Labels: bug

#59 Improve command line output for easier debugging
  masterthermconnect/__main__.py
  requirements.txt
Labels: enhancement

#64 Some updates for Registry Mappings
  masterthermconnect/const.py
  masterthermconnect/controller.py
  tests/test_config_data.py
Labels: enhancement
